name: Lakehouse ETL CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-etl:
    name: Run Spark ETL Unit and Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/unit

      - name: Run integration tests
        run: |
          pytest tests/integration

  deploy-step-function:
    name: Deploy Step Function Definition
    needs: test-etl
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Step Function definition
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn ${{ secrets.STEP_FUNCTION_ARN }} \
            --definition file://orchestration/step_function_definition.json
